### PR TITLE
Add function tts_override()

### PR DESCRIPTION
**Pull request by padthaitofuhot**
Mappings configuable in ini file:
tts_override["find"] = "replace"
Helps with user preferences and localization.
Prereq for my other PRs.

### CODE REVIEW

**Comment by DBnR1** [comment]
Merged. Can you send me your .ini configs for tts_override so I can add some of them to the default .ini?

**Comment by padthaitofuhot** [comment]
; Text-to-speech pronunciation overrides
tts_override["1"] = " one "
tts_override["2"] = " two "
tts_override["3"] = " tree "
tts_override["4"] = " four "
tts_override["5"] = " five "
tts_override["6"] = " six "
tts_override["7"] = " seven "
tts_override["8"] = " eight "
tts_override["9"] = " niner "
tts_override["0"] = " zero "
;tts_override[" - "] = " dash "
tts_override["-"] = " tack "
tts_override["&"] = " and "
; EM dash (—) is 0.5s delay.
tts_override[":"] = ". —"

**Comment by DBnR1** [comment]
Thanks. I'm currently migrating from the .ini style configuration do db based configuration. It's just easier to keep peoples configurations up-to-date that way.

**Comment by padthaitofuhot** [comment]
I kind of like having the INI file right in the EDTB so I can fiddle with it, but I do see your point. Would it be possible to keep an INI file around for plugins and user scripts?  Having that $settings global is super great.

**Comment by DBnR1** [comment]
The way I did it is the db based settings extend the $settings global, and some of the settings are still in the .ini file (like the directories, etc. that are set during install).
So yeah, the .ini stays :)

**Comment by padthaitofuhot** [comment]
Cheers!  Thank you!

**Pull request merged**
